### ISSUE TITLE
Issue with Generic relations in new versions of Django

### ISSUE THREAD

**Issue by stml** [bitlabstudio/django-multilingual-tags#3]
The django.contrib.contenttypes module has been [reorganized](https://docs.djangoproject.com/en/dev/releases/1.7/#reorganization-of-django-contrib-contenttypes) as of Django 1.7.

As a result, it's no longer possible to add a GenericRelation to a model in the way you specify.

I believe this can be fixed with the [new Generic relations system](https://docs.djangoproject.com/en/1.9/ref/contrib/contenttypes/#generic-relations) - but am somewhat at a loss as how to do it. Any ideas?

Many thanks.

**Comment by Tyrdall** [comment]
@stml Done in this commit: https://github.com/bitlabstudio/django-multilingual-tags/commit/1379aa946d123245e212c806cd5c438f78373cbc

Are you using the latest version?

**Comment by stml** [comment]
Thanks for your response. It's a hosted version transferring to Heroku, so I can only use the version available via pip. Is that the latest version?

**Comment by Tyrdall** [comment]
Yes https://pypi.python.org/pypi/django-multilingual-tags/0.9.1

**Comment by stml** [comment]
In that case, how should the Generic relationship you specify in the Usage section of the readme be altered?

**Comment by stml** [comment]
(I'm trying to add multilingual tags to objects in a directory, administered by Admins.)

**Comment by Tyrdall** [comment]
Ah! The README was outdated. Fixed it!

**Comment by stml** [comment]
Great, thanks!
